export default function Serviciu() {
    return (
        <div className="py-12">
            <h1 className="text-center text-4xl font-bold mb-10">Consiliere de dezvoltare personala</h1>
            <div className="max-w-6xl mx-auto flex space-y-4 flex-col px-4">
                <p className="text-justify">L-aș contrazice, cu modestie, pe Malraux: Nu religios va fi secolul acesta, ci spiritual. Și nu pentru că ar fi ceva în neregulă cu religiile, ci pentru că noi, oamenii, nu am știut să utlilizăm corespunzător prețioasele informații ascunse între paginile cărților sacre. Întoarcerea către vechile practici spirituale este una dintre conseciențele eșecului nostru de comprehensiune sau de hermeneutică a mesajului mesianic. Valorile primite de la Iisus sunt inestimabile. Iubirea este darul cel mai de preț primit de la el și, totuși, în primele secole creștine, cei prigoniți au devenit abuzatori. E un fenomen binecunoscut în psihologie. Triunghiul relațional Victimă-Abuzator-Salvator este o formă toxică pentru cei implicați. Într-o familie disfuncțională, de exemplu, membrii joacă pe rând cele trei roluri. Se pot sustrage din lanțul cauzal doar cei care reușesc să se vindece emoțional. Altfel, repetă la infinit roluri care îi fac nefericiți și toxici atât pentru ei cât și pentru ceilalți. Extrapolând, marea familie creștină a ieșit nevindecată din cunoscuta prigoană care a durat până în secolul IV. Nu a avut timp să se maturizeze &quot;emoțional&quot;, pentru că împăratul creștin Constantin cel Mare a decretat religia creștină religie &quot;licită&quot; (acceptată printre celelalte, precreștine), apoi religie de stat. Dintr-odată regină, religia (mă refer desigur la exponenții săi) nu a știut ce să facă cu puterea, devenind din victimă abuzator. În numele blândului Iisus, creștinii au ucis, persecutat, abuzat – adică exact ceea ce Iisus propovăduise să nu facă. Exemplul celebrei femei filosof Hypatia din Alexandria, care a fost ucisă cu o cruzime inimaginabilă de creștini, doar pentru că a refuzat să renunțe la ideile ei filosofice, de altfel pașnice, este unul extrem de elocvent în acest sens.</p>

                <p className="text-justify">Un alt motiv pentru care auzim tot mai des vorbindu-se în zilele noastre despre spiritualitate este cel al conștientizării răului pe care aceeași specie, omul, o produce pământului prin actele sale nesăbuite. O idee greșit înțeleasă din Biblie și cultivată de secole în rândul credincioșilor, în principal de prelați, este aceea că pământul ne aparține și că animalele au fost create de Dumnezeu ca să ne folosim noi, de ele, după bunul nostru plac. Aud adesea persoane care frecventează biserica zicând că animalele nu au suflet. Cu alte cuvinte, putem să ne purtăm oricum cu ele. Să le lovim, să le batjocorim, să le ucidem și să le mâncăm. Încă mai există în satele românești fenomenul de tăiere a porcului, o perioadă sinistră, care are loc în zilele premergătoare Crăciunului. Pe scurt, se strâng mai mulți credincioși în jurul porcului legat, care se zbate, și îl înjunghie. E o distracție pentru ei. Se zice că porcul știe cu o zi înainte că urmează să fie sacrificat, nu am habar cum, dar știe. Plânge cu groază toată noaptea. Ca noi toți, porcul se teme de moarte. La fel se întâmplă cu mieii și cu iezii de Paști, o altă sărbătoare centrată pe rememorarea zilelor în care Iisus a propovăduit iubirea, compasiunea și pacea. Dar Iisus nu a mâncat niciodată carne de porc, fiind evreu. De Paștele iudaic, tradiția culinară era orientată spre consumul de miel. Or, Iisus nici măcar miel nu a mâncat, pentru că Iisus știa că prin consumul de carne nivelul energetic scade dramatic și, odată cu el, și puterea vindecătoare. Cel mult Iisus ar fi putut mânca pește. Nu vă întrebați de ce oare în interiorul mânăstirilor, indiferent de orientare religioasă, călugării nu mănâncă niciodată carne? Am auzit pe unii și pe alții că asceții nu muncesc, motiv pentru care nu au nevoie de proteine. Greșit. O mânăstire este o comunitate umană în miniatură, fiecare membru are atribuții și da, în afară de închinăciune, acolo se muncește din greu.</p>

                <p className="text-justify">Cât despre pământ, ideea greu de înțeles pentru unii e că nu ne aparține. Pământul e doar o gazdă, minunată și primitoare, atât pentru noi cât și pentru celelalte specii. Simțul proprietății ne-a dezumanizat, așa cum avea să observe filosoful francez Jean Jacques Rousseau? Posibil. Pofta de înavuțire, lăcomia, egoismul, aceste trăsături specifice doar omului, dintre toți locuitorii planetei, au dus, în timp, la deteriorarea dramatică a acesteia. Cutremure, tsunami, incendii de păduri și inundații – tot atâtea consecințe ale actelor reprobabile ale omului: construcții din beton, munți de gunoaie, defrișări fără discernământ, exploatări miniere etc. Sigur că schimbări planetare apar oricum, schimbarea e un act necesar al evoluției. Dar poate că există și alte căi de metamorfozare. La urma urmei, fluturele iese din cocon natural, nu în urma unor traume sau fărădelegi. În contextul global actual, așa de deprimant, vechi forme de spiritualitate, așa cum este și &quot;șamanismul&quot;, apar ca un pansament blând și eficient pentru spiritele rănite în lupta fără sens care se numește viețuire, iar calea de vindecare pe care ne-o propun rezidă în reconectarea omului cu natura și, în cele din urmă, cu adevăratul său sine.</p>

                <p className="text-justify">În sens șamanic, toate bolile vin din dezechilibru și înstrăinare în relație cu natura, cu ceilalți, cu noi înșine. Conștientizarea importanței acestei relații pentru sănătatea noastră, a tuturor, e primul pas spre vindecare. Așa cum arată PhD Steve Serr, &quot;o reconectare umană completă cu pământul nostru este o cerință pentru sustenabilitatea nu doar a planetei, ci și a umanității. Bolile de care suferim, din punct de vedere psihologic, social și ecologic se datorează, în mare măsură, atitudinii noastre greșite față de pământ. Trebuie să pricepem odată pentru totdeauna că acțiunile noastre de azi ne îndreaptă spre dezastru&quot;.</p>

                <p className="text-justify">Însă de 10 ani încoace, specialiștii în cercetarea și practicarea hipnozei au căzut oarecum de acord cu privire la faptul că hipnoza poate fi definită drept o stare naturală de concentrare și atenție în care capacitatea de a primi sugestii este sporită. Pentru orice om, stările modificate ale conștiinței sunt o parte naturală a vieţii cotidiene. Trecerea de la somn la starea de trezire, visarea cu ochii deschiși sau senzația pierderii timpului când suntem complet absorbiți de o activitate preferată sunt toate exemple moderne de stări modificate de conștiință [American Society of Clinical Hypnosis, 2013].</p>
            </div>
        </div>
    )
}