import Navbar from '@/components/navbar'
import './globals.css'
import { Montserrat_Alternates } from 'next/font/google'
import { Footer } from '@/components/footer'
import CustomCursor from '@/components/custom-cursor'
import Script from 'next/script'

const inter = Montserrat_Alternates({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomCursor />
        <Navbar />
        {children}
        <Footer />
      {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js" /> */}      
      
      </body>
    </html>
  )
}
